<?php

return [
    'pending' => [
        'label' => 'Order Placed',
        'icon' => 'bx bx-receipt',
        'color' => '#64748b',
        'bg_color' => '#f1f5f9',
        'border_color' => '#cbd5e1',
        'next' => ['paid', 'canceled'],
        'tooltip' => 'Order has been placed and is awaiting payment.',
        'description' => 'Order placed successfully',
    ],
    'paid' => [
        'label' => 'Payment Confirmed',
        'icon' => 'bx bx-credit-card',
        'color' => '#2563eb',
        'bg_color' => '#dbeafe',
        'border_color' => '#3b82f6',
        'next' => ['shipped', 'canceled'],
        'tooltip' => 'Payment received and confirmed.',
        'description' => 'Payment received successfully',
    ],
    'shipped' => [
        'label' => 'Shipped',
        'icon' => 'bx bx-car',
        'color' => '#0ea5e9',
        'bg_color' => '#e0f2fe',
        'border_color' => '#0ea5e9',
        'next' => ['completed', 'canceled'],
        'tooltip' => 'Order has been shipped and is on its way.',
        'description' => 'Order shipped successfully',
    ],
    'completed' => [
        'label' => 'Delivered',
        'icon' => 'bx bx-check-double',
        'color' => '#6b7280',
        'bg_color' => '#f3f4f6',
        'border_color' => '#d1d5db',
        'next' => [],
        'tooltip' => 'Order delivered successfully.',
        'description' => 'Order delivered successfully',
    ],
    'canceled' => [
        'label' => 'Canceled',
        'icon' => 'bx bx-block',
        'color' => '#ef4444',
        'bg_color' => '#fef2f2',
        'border_color' => '#ef4444',
        'next' => [],
        'tooltip' => 'Order was canceled.',
        'description' => 'Order has been canceled',
    ],
    'refunded' => [
        'label' => 'Refunded',
        'icon' => 'bx bx-undo',
        'color' => '#8b5cf6',
        'bg_color' => '#f3e8ff',
        'border_color' => '#8b5cf6',
        'next' => [],
        'tooltip' => 'Order has been refunded.',
        'description' => 'Order refunded',
    ],
    'returned' => [
        'label' => 'Returned',
        'icon' => 'bx bx-rotate-left',
        'color' => '#f97316',
        'bg_color' => '#fed7aa',
        'border_color' => '#f97316',
        'next' => ['refunded'],
        'tooltip' => 'Order has been returned.',
        'description' => 'Order returned',
    ],
];
